### PR TITLE
restrict regular user access

### LINKED ISSUE #5: Messaging: ejabberd abschotten
Vor production sollten wir uns die ejabberd.yml config nochmal genauer angucken und die Nutzung für fremde User verhindern. 

https://www.coverfire.com/archives/2009/10/17/ejabberd-default-permissions/ (alt, aber wer weiß ob sich da was geändert hat)

### PR DESCRIPTION
**Pull request by marcusg**
* disable registration
* disable muc creation

fixes #5

### CODE REVIEW

**Comment by marcusg** [comment]
fixes #5

**Comment by Jack12816** [comment]
I would like to stick to the open settings here and do these changes on the custom images. What do you think?

**Comment by Jack12816** [comment]
See: https://github.com/hausgold/docker-ejabberd/pull/14

**Comment by Jack12816** [comment]
Closed and relocated. https://github.com/hausgold/docker-ejabberd/pull/14 https://github.com/hausgold/maklerportal-api/pull/479

**Pull request closed without merging**
